export {default as brain} from './brain.png';
export {default as capsule} from './capsule.png';
export {default as email} from './email.png';
export {default as facebook} from './facebook.png';
export {default as femme} from './femme.jpg'
export {default as linkedin} from './linkedin.png';
export {default as localisation} from './localisation.png';
export {default as logoPharmacie} from './LogoPharma.png';
export {default as phone} from './phone.png';
export {default as shield} from './shield.png';
export {default as deuxFemme} from './deuxFemme.jpg';
export {default as deuxFemmeXl} from './deuxFemme.png';
export {default as infirmier} from './infirmier.jpg';
export {default as infirmierXl} from './infirmier.png';
export {default as pharmacieHouse} from './pharmacieHouse.png'
export {default as pharmacieHouseSm} from './pharmacieHouse.jpg'