export {default as brain} from './brain.png';
export {default as capsule} from './capsule.png';
export {default as email} from './email.png';
export {default as facebook} from './facebook.png';
export {default as femme} from './femme.jpg'
export {default as linkedin} from './linkedin.png';
export {default as localisation} from './localisation.png';
export {default as logoPharmacie} from './LogoPharma.png';
export {default as phone} from './phone.png';
export {default as shield} from './shield.png';
export {default as deuxFemme} from './deuxFemme.jpg';
export {default as deuxFemmeXl} from './deuxFemme.png';
export {default as infirmier} from './infirmier.jpg';
export {default as infirmierXl} from './infirmier.png';
export {default as pharmacieHouse} from './pharmacieHouse.png'
export {default as pharmacieHouseSm} from './pharmacieHouse.jpg'
export {default as bledina} from './bledina.png'
export {default as cheveux} from './cheveux.jpg'
export {default as ericFavre} from './ericFavre.png'
export {default as laroche} from './laroche.png'
export {default as maman} from './maman.jpg'
export {default as noreva} from './noreva.png'
export {default as sport} from './sport.jpg'
export {default as topicrem} from './topicrem.png'
export {default as vichy} from './vichy.png'
export {default as actipurGammeNoreva} from './actipurGamme.jpg'
export {default as actipurStopNoreva} from './actipurStop.png'
export {default as actipurSoinNoreva} from './activpur.png'
export {default as biberonRemond} from './biberonRemond.png'
export {default as eauMicellaireTopicrem} from './EauMice.png'
export {default as claPreviewEricfavre} from './fatBurnerEfv.jpg'
export {default as claProductEricfavre} from './fatBurnerEfv1.jpg'
export {default as goubillonRemond} from './goupillon.png'
export {default as ironEricfavre} from './ironEfv.jpg'
export {default as isoZeroLgEricfavre} from './isoZeroEfv1.5.png'
export {default as isoZeroSlEricfavre} from './isoZeroEfv500.png'
export {default as ultraHydratantTopicrem} from './lait200.png'
export {default as lipikarSyndetLrp} from './lipkar.jpg'
export {default as melaDayTopicrem} from './mela.png'
export {default as melaDayGammeTopicrem} from './melaGamme.jpg'
export {default as noreliftNoreva} from './norelifteGamme.jpg'
export {default as normadermNoreva} from './normaderm.jpg'
export {default as pancakesEricfavre} from './pancakeEfv.jpg'
export {default as tetineRemond} from './tetineCaoutchouc.png'
export {default as tolerianeLrp} from './toleriane.jpg'
export {default as wheyLgEricfavre} from './whey1.5.jpg'
export {default as wheySmEricfavre} from './whey500.jpg'
export {default as zmaEricfavre} from './zmaEfv.jpg'
export {default as zmaPreviewEricfavre} from './zmfEfv.jpg'
export {default as nursie} from './Nursie.png'
export {default as physio} from './physiolac.png'
export {default as inhalation} from './inhalation.png'
export {default as bfm} from './bfm.png'
export {default as nyhavana} from './nyhavana.png'
export {default as sanlam} from './sanlam.png'
export {default as pharmaDestin} from './pharmaDestin.png'
export {default as logoPharmacieXl} from './logopharmacie.png'