export {default as brain} from './brain.png';
export {default as capsule} from './capsule.png';
export {default as email} from './email.png';
export {default as facebook} from './facebook.png';
export {default as femme} from './femme.jpg'
export {default as linkedin} from './linkedin.png';
export {default as localisation} from './localisation.png';
export {default as logoPharmacie} from './LogoPharma.png';
export {default as phone} from './phone.png';
export {default as shield} from './shield.png';